CREATE USER bbb WITH PASSWORD '123456';
CREATE DATABASE bbb OWNER bbb;
GRANT ALL PRIVILEGES ON DATABASE bbb to bbb;

CREATE USER cybex WITH PASSWORD '123456';
CREATE DATABASE cybex OWNER cybex;
GRANT ALL PRIVILEGES ON DATABASE cybex to cybex;

CREATE USER saas WITH PASSWORD '123456';
CREATE DATABASE saas OWNER saas;
GRANT ALL PRIVILEGES ON DATABASE saas to saas;
